# Generated by Django 5.2.16 on 2026-07-13 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=200, verbose_name='中文名')),
                ('scientific_name', models.CharField(max_length=200, unique=True, verbose_name='學名／拉丁名')),
                ('taicol_taxon_id', models.CharField(blank=True, default='', max_length=50, verbose_name='TaiCOL 物種編號')),
                ('taxon_group', models.CharField(choices=[('bird', '鳥'), ('insect', '昆蟲'), ('bat', '蝙蝠'), ('flying_squirrel', '飛鼠')], max_length=20, verbose_name='分類群')),
                ('order', models.CharField(blank=True, default='', max_length=100, verbose_name='目 (Order)')),
                ('family', models.CharField(blank=True, default='', max_length=100, verbose_name='科 (Family)')),
                ('genus', models.CharField(blank=True, default='', max_length=100, verbose_name='屬 (Genus)')),
                ('conservation_status', models.CharField(choices=[('general', '一般類'), ('other', '其他應予保育'), ('rare', '珍貴稀有'), ('endangered', '瀕臨絕種')], default='general', max_length=20, verbose_name='保育等級（台灣）')),
                ('iucn_status', models.CharField(choices=[('LC', 'LC 無危'), ('NT', 'NT 接近受脅'), ('VU', 'VU 易危'), ('EN', 'EN 瀕危'), ('CR', 'CR 極危'), ('DD', 'DD 資料不足'), ('NE', '未評估')], default='NE', max_length=2, verbose_name='保育等級（IUCN）')),
            ],
            options={
                'verbose_name': '物種',
                'verbose_name_plural': '物種',
                'ordering': ['taxon_group', 'scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('record_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='紀錄編號')),
                ('observer', models.CharField(blank=True, max_length=200, verbose_name='觀察者')),
                ('observation_date', models.DateField(blank=True, null=True, verbose_name='觀察日期')),
                ('observation_location', models.CharField(blank=True, max_length=300, verbose_name='觀察地點')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='數量')),
                ('data_source', models.CharField(choices=[('ebird', 'eBird'), ('yilan_bird', '宜蘭野鳥學會'), ('bat_society', '蝙蝠學會'), ('other', '其他')], max_length=20, verbose_name='資料來源')),
                ('source_reference', models.CharField(blank=True, max_length=500, verbose_name='來源網址或原始ID')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='collection.species', verbose_name='學名')),
            ],
            options={
                'verbose_name': '觀察紀錄',
                'verbose_name_plural': '觀察紀錄',
                'ordering': ['-observation_date', 'record_number'],
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('catalog_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='典藏編號')),
                ('specimen_type', models.CharField(choices=[('taxidermy', '剝製'), ('pinned', '針插'), ('fluid', '浸液'), ('skeleton', '骨骼')], max_length=20, verbose_name='標本類型')),
                ('collector', models.CharField(blank=True, max_length=200, verbose_name='採集者')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='採集日期')),
                ('collection_location', models.CharField(blank=True, max_length=300, verbose_name='採集地點')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度')),
                ('accession_date', models.DateField(blank=True, null=True, verbose_name='入藏日期')),
                ('source', models.CharField(choices=[('donation', '捐贈'), ('rescue', '救傷'), ('collection', '採集'), ('transfer', '移交')], max_length=20, verbose_name='來源')),
                ('preservation_status', models.CharField(blank=True, max_length=200, verbose_name='保存狀態')),
                ('storeroom', models.CharField(blank=True, max_length=100, verbose_name='庫房')),
                ('cabinet', models.CharField(blank=True, max_length=50, verbose_name='櫃號')),
                ('drawer', models.CharField(blank=True, max_length=50, verbose_name='抽屜號')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specimens/', verbose_name='標本影像')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='collection.species', verbose_name='學名')),
            ],
            options={
                'verbose_name': '標本',
                'verbose_name_plural': '標本',
                'ordering': ['catalog_number'],
            },
        ),
    ]
