# Generated by Django 5.2.16 on 2026-07-13 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='accession_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='入藏日期'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='catalog_number',
            field=models.CharField(blank=True, help_text='留空即依「分類群代碼-年份-流水號」自動產生（例：AVE-2026-0001）；也可自行填寫。', max_length=50, primary_key=True, serialize=False, verbose_name='典藏編號'),
        ),
    ]
