# Generated by Django 5.2.16 on 2026-07-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_specimen_accession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='hazard_markers',
            field=models.JSONField(blank=True, default=list, help_text='可複選；都不勾即代表「無」。曾以砷／汞／其他防蟲劑處理者請勾選。', verbose_name='危害標記'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='identified_by',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='鑑定者'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='identified_date',
            field=models.DateField(blank=True, null=True, verbose_name='鑑定日期'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='status',
            field=models.CharField(choices=[('in_storage', '在庫'), ('loaned', '借出'), ('on_display', '展示中'), ('under_repair', '待修復'), ('lost', '遺失')], default='in_storage', max_length=20, verbose_name='標本狀態'),
        ),
    ]
