# Generated by Django 5.2.16 on 2026-07-13 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_specimen_hazard_markers_specimen_identified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('loan_out', '借出'), ('return', '歸還'), ('repair', '送修'), ('display', '展示'), ('store_in', '入庫'), ('other', '其他')], max_length=20, verbose_name='異動類型')),
                ('movement_date', models.DateField(verbose_name='異動日期')),
                ('counterparty', models.CharField(blank=True, help_text='例：借給某大學、送某修復師。', max_length=300, verbose_name='對象單位或個人')),
                ('handler', models.CharField(blank=True, max_length=200, verbose_name='經手人')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='collection.specimen', verbose_name='標本')),
            ],
            options={
                'verbose_name': '異動紀錄',
                'verbose_name_plural': '異動紀錄',
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='specimen_images/', verbose_name='影像檔')),
                ('image_type', models.CharField(choices=[('body', '標本本體'), ('label', '原始標籤'), ('detail', '細節'), ('other', '其他')], max_length=20, verbose_name='影像類型')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='說明')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.specimen', verbose_name='標本')),
            ],
            options={
                'verbose_name': '標本影像',
                'verbose_name_plural': '標本影像',
                'ordering': ['id'],
            },
        ),
    ]
