# Generated by Django 5.2.16 on 2026-07-13 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_movement_specimenimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='建立時間'),
        ),
    ]
