# Generated by Django 5.2.16 on 2026-07-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_specimen_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identified_by', models.CharField(blank=True, max_length=200, verbose_name='鑑定者')),
                ('identified_date', models.DateField(verbose_name='鑑定日期')),
                ('basis', models.TextField(blank=True, help_text='例：依羽色、依標本標籤、參考文獻。', verbose_name='鑑定依據／備註')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否為現行鑑定')),
                ('identified_as', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifications', to='collection.species', verbose_name='鑑定為物種')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='collection.specimen', verbose_name='標本')),
            ],
            options={
                'verbose_name': '鑑定歷程',
                'verbose_name_plural': '鑑定歷程',
                'ordering': ['-identified_date', '-id'],
            },
        ),
    ]
