# Generated by Django 5.2.16 on 2026-07-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='introduction',
            field=models.TextField(blank=True, default='', help_text='公開頁面顯示的物種簡介。', verbose_name='物種介紹'),
        ),
    ]
