# Generated by Django 5.2.16 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_species_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新'),
        ),
    ]
