# Generated by Django 5.2.16 on 2026-07-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_species_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('live', '生態照'), ('detail', '細節特徵'), ('habitat', '棲地環境'), ('other', '其他')], max_length=20, verbose_name='影像類型')),
                ('is_primary', models.BooleanField(default=False, help_text='勾選後會顯示於檢索結果與詳細頁。', verbose_name='主要影像')),
                ('is_public', models.BooleanField(default=True, help_text='取消勾選則僅限館內人員檢視。', verbose_name='對外公開')),
                ('photographer', models.CharField(blank=True, max_length=100, verbose_name='攝影者')),
                ('license', models.CharField(choices=[('museum', '館方自攝'), ('cc0', 'CC0'), ('cc_by', 'CC BY'), ('cc_by_nc', 'CC BY-NC'), ('cc_by_sa', 'CC BY-SA'), ('other', '其他授權'), ('unverified', '未確認')], default='unverified', max_length=20, verbose_name='授權方式')),
                ('license_note', models.CharField(blank=True, help_text='選擇「其他授權」時請填寫授權來源與範圍。', max_length=200, verbose_name='授權備註')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='observation_images/', verbose_name='影像檔')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.observation', verbose_name='觀察紀錄')),
            ],
            options={
                'verbose_name': '觀察紀錄影像',
                'verbose_name_plural': '觀察紀錄影像',
                'ordering': ['-is_primary', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('live', '生態照'), ('detail', '細節特徵'), ('habitat', '棲地環境'), ('other', '其他')], max_length=20, verbose_name='影像類型')),
                ('is_primary', models.BooleanField(default=False, help_text='勾選後會顯示於檢索結果與詳細頁。', verbose_name='主要影像')),
                ('is_public', models.BooleanField(default=True, help_text='取消勾選則僅限館內人員檢視。', verbose_name='對外公開')),
                ('photographer', models.CharField(blank=True, max_length=100, verbose_name='攝影者')),
                ('license', models.CharField(choices=[('museum', '館方自攝'), ('cc0', 'CC0'), ('cc_by', 'CC BY'), ('cc_by_nc', 'CC BY-NC'), ('cc_by_sa', 'CC BY-SA'), ('other', '其他授權'), ('unverified', '未確認')], default='unverified', max_length=20, verbose_name='授權方式')),
                ('license_note', models.CharField(blank=True, help_text='選擇「其他授權」時請填寫授權來源與範圍。', max_length=200, verbose_name='授權備註')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='species_images/', verbose_name='影像檔')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collection.species', verbose_name='物種')),
            ],
            options={
                'verbose_name': '物種影像',
                'verbose_name_plural': '物種影像',
                'ordering': ['-is_primary', 'created_at'],
                'abstract': False,
            },
        ),
    ]
