# Generated by Django 5.2.16 on 2026-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_observationimage_speciesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='inaturalist_taxon_id',
            field=models.CharField(blank=True, default='', help_text='填入後將直接連往該物種頁面；留白則以學名查詢台灣觀察紀錄。', max_length=20, verbose_name='iNaturalist Taxon ID'),
        ),
    ]
