# Generated by Django 5.2.16 on 2026-07-20 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_species_inaturalist_taxon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='拾獲或入館日期，與採集日期不同時請分別填寫', null=True, verbose_name='取得日期'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('public_handin', '民眾拾獲送交'), ('staff_collect', '館員採集'), ('authority_transfer', '主管機關移交'), ('donation', '捐贈'), ('purchase', '收購'), ('exchange', '與他館交換'), ('other', '其他')], max_length=20, verbose_name='取得方式'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='cause_of_death',
            field=models.CharField(blank=True, choices=[('roadkill', '路殺'), ('window_strike', '窗殺'), ('electrocution', '電殺'), ('cat_dog', '貓犬咬傷'), ('suspected_poison', '疑似中毒'), ('entangle_bycatch', '纏繞或誤捕'), ('natural', '自然死亡'), ('confiscated', '查獲沒入'), ('unknown', '不明'), ('other', '其他')], help_text='與人為因素相關者，具展示詮釋價值，請盡量填寫', max_length=20, verbose_name='死亡原因'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='cause_of_death_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='死亡原因補述'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='preparation_date',
            field=models.DateField(blank=True, null=True, verbose_name='製作完成日期'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='preparation_status',
            field=models.CharField(choices=[('frozen_pending', '冷凍待處理'), ('in_progress', '製作中'), ('done', '已完成'), ('not_required', '無需製作'), ('other', '其他')], default='done', help_text='冰箱中尚未處理者請選「冷凍待處理」', max_length=20, verbose_name='製作狀態'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='preparer',
            field=models.CharField(blank=True, max_length=100, verbose_name='標本製作者'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='preservation_method',
            field=models.CharField(blank=True, choices=[('taxidermy', '剝製'), ('study_skin', '假剝製'), ('fluid', '浸液'), ('skeleton', '骨骼'), ('dried', '乾燥'), ('pinned', '針插'), ('frozen', '冷凍'), ('other', '其他')], max_length=20, verbose_name='保存方式'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='storage_location',
            field=models.CharField(blank=True, help_text='例如 典藏庫冷凍櫃A-3、標本室第2櫃', max_length=100, verbose_name='存放位置'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='accession_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='已停用，保留供歷史資料查考，請改用『取得日期』(acquisition_date)。', verbose_name='入藏日期'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collector',
            field=models.CharField(blank=True, help_text='主動採集者或民眾拾獲者皆填於此，來源性質請於『取得方式』欄位標示', max_length=200, verbose_name='採集者'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='preservation_status',
            field=models.CharField(blank=True, help_text='已停用，保留供歷史資料查考，請改用『保存方式』(preservation_method)。', max_length=200, verbose_name='保存狀態'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='source',
            field=models.CharField(blank=True, choices=[('donation', '捐贈'), ('rescue', '救傷'), ('collection', '採集'), ('transfer', '移交')], help_text='已停用，保留供歷史資料查考，請改用『取得方式』(acquisition_type)。', max_length=20, null=True, verbose_name='來源'),
        ),
    ]
