# Generated by Django 5.2.16 on 2026-07-20 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_specimen_acquisition_date_specimen_acquisition_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specimenimage',
            options={'ordering': ['-is_primary', 'created_at'], 'verbose_name': '標本影像', 'verbose_name_plural': '標本影像'},
        ),
        migrations.AddField(
            model_name='specimenimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specimenimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='勾選後會顯示於檢索結果與詳細頁。', verbose_name='主要影像'),
        ),
        migrations.AddField(
            model_name='specimenimage',
            name='is_public',
            field=models.BooleanField(default=True, help_text='取消勾選則僅限館內人員檢視。', verbose_name='對外公開'),
        ),
        migrations.AddField(
            model_name='specimenimage',
            name='license',
            field=models.CharField(blank=True, choices=[('museum', '館方自攝'), ('cc0', 'CC0'), ('cc_by', 'CC BY'), ('cc_by_nc', 'CC BY-NC'), ('cc_by_sa', 'CC BY-SA'), ('other', '其他授權'), ('unverified', '未確認')], default='unverified', max_length=20, verbose_name='授權方式'),
        ),
        migrations.AddField(
            model_name='specimenimage',
            name='license_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='授權備註'),
        ),
        migrations.AddField(
            model_name='specimenimage',
            name='photographer',
            field=models.CharField(blank=True, max_length=100, verbose_name='攝影者'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='image',
            field=models.ImageField(blank=True, help_text='已停用，請改用『標本影像』（可上傳多張的標本影像表）。', null=True, upload_to='specimens/', verbose_name='標本影像'),
        ),
    ]
