# Generated by Django 5.2.16 on 2026-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_copy_specimen_image_to_specimenimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='conservation_status',
            field=models.CharField(choices=[('general', '一般類'), ('other', '其他應予保育'), ('rare', '珍貴稀有'), ('endangered', '瀕臨絕種'), ('unverified', '待查證')], help_text='必選。不確定時請選「待查證」。凡非「一般類」（含待查證）者，公開頁一律採保護性處理：其觀察影像不對外顯示、標本地點僅到縣市層級。', max_length=20, verbose_name='保育等級（台灣）'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='collection_location',
            field=models.CharField(blank=True, help_text='請填至縣市與鄉鎮市區層級即可（例：宜蘭縣蘇澳鎮）。為保護保育類棲地、防範盜獵，請勿填入巷弄、門牌、確切巢位或棲所座標；精確座標請填於下方「緯度／經度」欄位（不會出現在公開頁）。', max_length=300, verbose_name='採集地點'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['data_source'], name='collection__data_so_5be933_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['observation_date'], name='collection__observa_e3e76f_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['taxon_group', 'scientific_name'], name='collection__taxon_g_27309c_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['conservation_status'], name='collection__conserv_5284e2_idx'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['status'], name='collection__status_368617_idx'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['preparation_status'], name='collection__prepara_2ade88_idx'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['cause_of_death'], name='collection__cause_o_8c2dc9_idx'),
        ),
    ]
