# Generated by Django 5.2.16 on 2026-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_specimen_taxon_group_identification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_auto_created',
            field=models.BooleanField(default=False, help_text='此筆物種資料由標本建檔時自動產生，請盡快補齊保育等級與分類資訊。', verbose_name='由標本建檔自動產生'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxon_group',
            field=models.CharField(choices=[('bird', '鳥'), ('insect', '昆蟲'), ('bat', '蝙蝠'), ('flying_squirrel', '飛鼠'), ('other', '其他')], max_length=20, verbose_name='分類群'),
        ),
    ]
