# Generated by Django 5.2.16 on 2026-07-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_species_is_auto_created_alter_species_taxon_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='public_description',
            field=models.TextField(blank=True, default='', help_text='顯示於公開檢索頁簡易版的物種介紹，建議 80 到 120 字，語氣平易近人。', verbose_name='公開簡介'),
        ),
    ]
