# Generated by Django 5.2.16 on 2026-07-21 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_backfill_occurrence_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='系統自動產生，作為 Darwin Core eventID，產生後不得變更。', unique=True, verbose_name='採集事件識別碼')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='採集日期')),
                ('collection_location', models.CharField(blank=True, help_text='請填至縣市與鄉鎮市區層級即可（例：宜蘭縣蘇澳鎮）。為保護保育類棲地、防範盜獵，請勿填入巷弄、門牌、確切巢位或棲所座標；精確座標請填於下方「緯度／經度」欄位（不會出現在公開頁）。', max_length=300, verbose_name='採集地點')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度')),
                ('collector', models.CharField(blank=True, help_text='主動採集者或民眾拾獲者皆填於此。', max_length=200, verbose_name='採集者')),
                ('habitat', models.CharField(blank=True, help_text='對應 Darwin Core habitat；選填。', max_length=300, verbose_name='棲地環境')),
                ('sampling_protocol', models.CharField(blank=True, choices=[('mist_net', '霧網'), ('light_trap', '燈光誘集'), ('sweep_net', '掃網'), ('trap', '陷阱'), ('found', '拾獲'), ('acoustic', '聲波偵測'), ('other', '其他')], help_text='對應 Darwin Core samplingProtocol；選填。', max_length=20, verbose_name='採集方法')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '採集事件',
                'verbose_name_plural': '採集事件',
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='specimen',
            name='collection_event',
            field=models.ForeignKey(blank=True, help_text='選填。來源不明的標本可留空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='collection.collectionevent', verbose_name='採集事件'),
        ),
    ]
