# Generated by Django 5.2.16 on 2026-07-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_backfill_collection_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='scientific_name_authorship',
            field=models.CharField(blank=True, help_text='學名的命名者與年份（對應 Darwin Core scientificNameAuthorship），例如 (Linnaeus, 1758)。可留空，之後由 TaiCOL 補齊。', max_length=200, null=True, verbose_name='學名命名者'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='individual_count',
            field=models.PositiveIntegerField(blank=True, help_text='此筆標本所含的個體數量（對應 Darwin Core individualCount）；預設不填，通常為 1。', null=True, verbose_name='個體數'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('egg', '卵'), ('larva', '幼蟲'), ('nymph', '若蟲'), ('pupa', '蛹'), ('juvenile', '幼體（幼鳥／幼獸）'), ('subadult', '亞成體'), ('adult', '成體／成蟲'), ('unknown', '不明')], help_text='標本個體的生活史階段。昆蟲可選卵／幼蟲／若蟲／蛹／成蟲；鳥類與獸類可選幼體／亞成體／成體。不確定請留空。', max_length=20, null=True, verbose_name='年齡階段'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='permit_number',
            field=models.CharField(blank=True, help_text='採集、持有或移交所依據的主管機關許可或公文文號（如野生動物保育相關許可）。可留空。', max_length=200, null=True, verbose_name='主管機關許可文號'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', '雄'), ('female', '雌'), ('unknown', '不明／未鑑別')], help_text='標本個體的性別，適用鳥／昆蟲／蝙蝠／飛鼠。無法辨別或不確定請選「不明／未鑑別」或留空。', max_length=20, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='source_institution',
            field=models.CharField(blank=True, help_text='標本的來源機關或單位，例如移交的主管機關、捐贈單位、野生動物收容或救傷單位等。', max_length=200, null=True, verbose_name='來源單位'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specimen_type',
            field=models.CharField(choices=[('taxidermy', '剝製'), ('pinned', '針插'), ('fluid', '浸液'), ('skeleton', '骨骼'), ('slide', '玻片')], max_length=20, verbose_name='標本類型'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='status',
            field=models.CharField(choices=[('in_storage', '在庫'), ('loaned', '借出'), ('on_display', '展示中'), ('under_repair', '待修復'), ('damaged', '毀損'), ('lost', '遺失')], default='in_storage', max_length=20, verbose_name='標本狀態'),
        ),
    ]
