# Generated by Django 5.2.16 on 2026-07-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0022_species_scientific_name_authorship_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-observation_date', 'record_number'], 'permissions': [('can_publish_observation', '可將觀察紀錄設為公開')], 'verbose_name': '觀察紀錄', 'verbose_name_plural': '觀察紀錄'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['taxon_group', 'scientific_name'], 'permissions': [('can_publish_species', '可將物種設為公開')], 'verbose_name': '物種', 'verbose_name_plural': '物種'},
        ),
        migrations.AlterModelOptions(
            name='specimen',
            options={'ordering': ['catalog_number'], 'permissions': [('can_publish_specimen', '可將標本設為公開')], 'verbose_name': '標本', 'verbose_name_plural': '標本'},
        ),
        migrations.AddField(
            model_name='observation',
            name='publication_status',
            field=models.CharField(choices=[('draft', '草稿'), ('review', '待審'), ('published', '公開')], db_index=True, default='draft', help_text='僅「公開」狀態的觀察紀錄會顯示於對外頁面與公開統計。', max_length=20, verbose_name='公開狀態'),
        ),
        migrations.AddField(
            model_name='species',
            name='publication_status',
            field=models.CharField(choices=[('draft', '草稿'), ('review', '待審'), ('published', '公開')], db_index=True, default='draft', help_text='僅「公開」狀態的資料會顯示於對外檢索、物種頁與公開統計。', max_length=20, verbose_name='公開狀態'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='publication_status',
            field=models.CharField(choices=[('draft', '草稿'), ('review', '待審'), ('published', '公開')], db_index=True, default='draft', help_text='僅「公開」狀態的標本會顯示於對外頁面與公開統計。', max_length=20, verbose_name='公開狀態'),
        ),
    ]
