# Generated by Django 5.2.16 on 2026-07-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0025_revoke_admin_publish_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specimen',
            options={'ordering': ['catalog_number'], 'permissions': [('can_publish_specimen', '可將標本設為公開'), ('can_export_full_data', '可匯出全部典藏資料')], 'verbose_name': '標本', 'verbose_name_plural': '標本'},
        ),
    ]
