# Generated by Django 5.2.16 on 2026-07-23 06:01

import collection.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_assign_full_export_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationimage',
            name='image',
            field=models.ImageField(upload_to='observation_images/', validators=[collection.validators.validate_specimen_image], verbose_name='影像檔'),
        ),
        migrations.AlterField(
            model_name='speciesimage',
            name='image',
            field=models.ImageField(upload_to='species_images/', validators=[collection.validators.validate_specimen_image], verbose_name='影像檔'),
        ),
        migrations.AlterField(
            model_name='specimenimage',
            name='image',
            field=models.ImageField(upload_to='specimen_images/', validators=[collection.validators.validate_specimen_image], verbose_name='影像檔'),
        ),
    ]
