# Generated by Django 5.2.16 on 2026-07-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_alter_observationimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='taxon_group',
            field=models.CharField(choices=[('bird', '鳥類'), ('insect', '昆蟲'), ('bat', '蝙蝠'), ('flying_squirrel', '飛鼠'), ('other', '其他')], max_length=20, verbose_name='分類群'),
        ),
    ]
