# Generated by Django 5.2.16 on 2026-07-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0032_backfill_accession_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='other_common_names',
            field=models.CharField(blank=True, default='', help_text='物種的其他中文俗名或別名，多個請以頓號「、」分隔，例如：魚狗、釣魚翁。', max_length=255, verbose_name='其他中文名'),
        ),
    ]
