# Generated by Django 5.2.16 on 2026-08-03 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0033_species_other_common_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogNumberChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_catalog_number', models.CharField(max_length=50, verbose_name='原典藏編號')),
                ('new_catalog_number', models.CharField(max_length=50, verbose_name='新典藏編號')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改時間')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_number_changes', to='collection.specimen', verbose_name='標本')),
            ],
            options={
                'verbose_name': '典藏編號異動',
                'verbose_name_plural': '典藏編號異動',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
