# Generated by Django 5.2.16 on 2026-08-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0034_catalognumberchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='學名'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name_authorship',
            field=models.CharField(blank=True, help_text='學名的命名者與年份（對應 Darwin Core scientificNameAuthorship），例如 (Linnaeus, 1758)。可留空，之後由 TaiCOL 補齊。', max_length=200, null=True, verbose_name='命名者/年代'),
        ),
    ]
