"""
Django settings for lymuseum project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 預設關閉 DEBUG（正式模式）；開發時設環境變數 DJANGO_DEBUG=True 開啟。
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY 一律優先由環境變數 DJANGO_SECRET_KEY 提供：
# - 正式環境（DEBUG=False）未設定 → 直接 raise，絕不靜默使用預設值
#   （舊的硬編碼 fallback 已存在於公開 git 歷史，繼續沿用並不安全）。
# - 本機開發（DEBUG=True）未設定 → 使用明確標示「僅供開發」的暫時金鑰。
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-not-for-production'
    else:
        raise ImproperlyConfigured(
            '未設定環境變數 DJANGO_SECRET_KEY。正式環境必須提供一組長且隨機的'
            '金鑰；請在 Render 的 Environment 設定 DJANGO_SECRET_KEY 後再啟動。'
        )

# 允許的主機（逗號分隔）；正式上線請把實際網域加進 DJANGO_ALLOWED_HOSTS。
ALLOWED_HOSTS = [
    h.strip() for h in
    os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',')
    if h.strip()
]

# Render 會自動提供部署網域於 RENDER_EXTERNAL_HOSTNAME，自動納入允許主機。
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CSRF 信任來源（HTTPS 網域）；Render 網域與自訂 DJANGO_CSRF_TRUSTED_ORIGINS 皆納入。
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in
    os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# HTTPS 安全強化：僅在正式 TLS 環境開啟（設環境變數 DJANGO_HTTPS=True）。
# 預設關閉，避免本機以 http 測試時 secure cookie 造成無法登入後台。
SECURE_HTTPS = os.environ.get('DJANGO_HTTPS', 'False') == 'True'
if SECURE_HTTPS:
    SECURE_SSL_REDIRECT = True          # 一律轉向 HTTPS
    SESSION_COOKIE_SECURE = True        # session cookie 僅走 HTTPS
    CSRF_COOKIE_SECURE = True           # CSRF cookie 僅走 HTTPS
    SECURE_HSTS_SECONDS = 31536000      # HSTS 一年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # 部署在反向代理／負載平衡器後時，依此標頭辨識原始請求為 HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    # django-unfold 必須排在 django.contrib.admin 之前
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    # 標本批次匯入的後台樣式（須排在 django.contrib.admin 之前，覆寫 import-export 模板）
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 標本批次匯入（django-import-export）
    'import_export',
    # Cloudinary 媒體儲存（僅在設定 CLOUDINARY_URL 時實際生效）
    'cloudinary_storage',
    'cloudinary',
    'collection',
]

# django-import-export：全程使用交易，任一列出錯即整批 rollback（保護資料一致性）
IMPORT_EXPORT_USE_TRANSACTIONS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise 需緊接在 SecurityMiddleware 之後，供正式模式下的靜態檔服務
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lymuseum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lymuseum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 資料庫：正式環境用 PostgreSQL（Render 提供 DATABASE_URL）；
# 本機若未設 DATABASE_URL，自動 fallback 回 SQLite，方便開發測試。
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,        # 連線重用，降低建立連線的開銷
            ssl_require=not DEBUG,    # 正式環境要求 SSL；本機除錯不強制
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

# 專案層級翻譯覆寫（優先於 Django/unfold 內建 catalog）。
# 用於將登入頁「忘記密碼」等字串改為指定的繁體中文，
# 不需修改 unfold 或 Django 套件內的檔案。
LOCALE_PATHS = [BASE_DIR / 'locale']

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic 的輸出目錄；WhiteNoise 由此提供靜態檔
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # WhiteNoise：壓縮靜態檔（不使用 manifest，避免第三方 CSS 參照缺檔而失敗）
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# 媒體檔（上傳的標本影像等）：
# - 設了環境變數 CLOUDINARY_URL → 存到 Cloudinary（Render 磁碟會掉檔，故用外部儲存）。
#   cloudinary 套件會自動讀取 CLOUDINARY_URL，金鑰不寫死在程式碼。
# - 未設 → fallback 回本機檔案儲存，方便本機開發測試。
if os.environ.get('CLOUDINARY_URL'):
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

# Media files (uploaded specimen images)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging
# 正式環境（DEBUG=False）時，Django 預設的 console handler 帶有 require_debug_true
# 過濾器，未捕捉例外的 Traceback 不會印到 stdout，導致 Render Logs 只看得到 HTTP
# 存取紀錄。以下自訂 console handler 直接輸出到 sys.stdout、且「不加任何 require_debug
# 過濾器」，讓 500 錯誤的完整 Traceback 出現在 Render Logs。此設定不受 DEBUG 影響，
# DEBUG=False 時同樣生效——且絕不需要、也不應該把 DEBUG 打開。
#
# 安全性：這裡只輸出例外堆疊與請求「路徑」。Django 的 django.request 錯誤紀錄本身
# 不含 request.POST／body／cookies／session，我們也未加入任何會傾印請求內容或環境
# 變數的 filter／formatter，因此不會把帳密等敏感資訊寫進 log。
#
# 詳細程度由環境變數 DJANGO_LOG_LEVEL 控制（預設 INFO），日後不改程式碼即可調整。
DJANGO_LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    # 保留 Django 內建 logger，避免關掉既有紀錄
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            # 時間、等級、logger 名稱、訊息
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose',
            # 刻意不設 'filters'：不加 require_debug_true，DEBUG=False 時仍輸出
        },
    },
    'loggers': {
        # 未捕捉例外（500）與完整 Traceback 的來源；固定 ERROR，一律輸出
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            # 不再往上傳給 'django'，避免重複輸出
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
        },
        # 專案自己的 app
        'collection': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        # Cloudinary 上傳過程（方便在 Render Logs 觀察）
        'cloudinary': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'cloudinary_storage': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
    },
}


# 寄信設定（供後台「忘記密碼」重設信使用）
# 一律由環境變數控制，不把任何帳號密碼寫進程式碼。
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# DEBUG 或未設定 EMAIL_HOST 時一律用 console backend（不實際寄信、印到主控台/log）。
if DEBUG or not EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# django-unfold 後台外觀設定
# https://unfoldadmin.com/docs/
UNFOLD = {
    "SITE_TITLE": "蘭陽博物館 飛行生物典藏系統",
    "SITE_HEADER": "蘭陽博物館 飛行生物典藏系統",
    # 自訂首頁儀表板
    "DASHBOARD_CALLBACK": "collection.dashboard.dashboard_callback",
    # 全站後台載入：關閉文字欄位自動完成（含登入頁）
    "SCRIPTS": [
        lambda request: static("collection/js/no_autocomplete.js"),
    ],
    # material symbols 圖示名稱，顯示在側欄標題旁
    "SITE_SYMBOL": "flutter_dash",
    # logo 先不放，之後可在此指定（可用 static() 指向 logo 檔）
    # "SITE_LOGO": lambda request: static("collection/logo.svg"),
    # 不設 THEME → 保留右上角深色／淺色切換鈕，使用者可自行切換
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "COLORS": {
        # 深藍色階（Tailwind blue），與蘭博識別相近
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "典藏管理",
                "separator": True,
                "items": [
                    {
                        "title": "物種",
                        "icon": "pets",
                        "link": reverse_lazy("admin:collection_species_changelist"),
                    },
                    {
                        "title": "標本",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:collection_specimen_changelist"),
                    },
                    {
                        "title": "觀察紀錄",
                        "icon": "visibility",
                        "link": reverse_lazy("admin:collection_observation_changelist"),
                    },
                ],
            },
            {
                "title": "統計報表",
                "separator": True,
                "items": [
                    {
                        "title": "查看統計",
                        "icon": "bar_chart",
                        "link": reverse_lazy("staff_stats"),
                    },
                ],
            },
            {
                "title": "資料管理",
                "separator": True,
                "items": [
                    {
                        "title": "資料備份",
                        "icon": "backup",
                        "link": reverse_lazy("backup_database"),
                        # 僅有備份權限者可見（後端仍會強制檢查）
                        "permission": lambda request: request.user.has_perm(
                            "collection.can_backup_database"
                        ),
                    },
                    {
                        "title": "資料還原",
                        "icon": "settings_backup_restore",
                        "link": reverse_lazy("restore_database"),
                        "permission": lambda request: request.user.has_perm(
                            "collection.can_restore_database"
                        ),
                    },
                    {
                        "title": "全欄位匯出",
                        "icon": "table_view",
                        "link": reverse_lazy("full_export"),
                        # 僅有匯出權限者可見（後端 view 仍會強制檢查）
                        "permission": lambda request: request.user.has_perm(
                            "collection.can_export_full_data"
                        ),
                    },
                    {
                        "title": "Darwin Core 匯出",
                        "icon": "public",
                        "link": reverse_lazy("darwin_core_export"),
                        # 對外標準化子集（GBIF／TBIA）；比照全欄位匯出的匯出權限，
                        # 僅有匯出權限者可見（後端 view 仍會強制檢查）。
                        "permission": lambda request: request.user.has_perm(
                            "collection.can_export_full_data"
                        ),
                    },
                ],
            },
            {
                "title": "認證授權",
                "separator": True,
                "items": [
                    {
                        "title": "使用者",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "群組",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
